language: python
python:
  - "3.4"

env:
  - DJANGO=1.8.4
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install pep8 --use-mirrors
  - pip install -q -e . --use-mirrors
  - pip install -r requirements.txt

before_script:
  - "pep8 --exclude=migrations --ignore=E501,E225 src"
  - pyflakes -x W src
script: 
  -python views.py test

